/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.app;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class App {
    public static void main(String[] args) {
        try {
            BufferedReader reader = new BufferedReader(new FileReader("./src/main/resources/prospects.txt"));
            String line = reader.readLine(); // skip the first line
            int i = 1;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                String name = parts[0];
                double totalLoan = Double.parseDouble(parts[1]);
                double interest = Double.parseDouble(parts[2]);
                int years = Integer.parseInt(parts[3]);
    
                int payments = years * 12;
                double monthlyInterest = interest / 12 / 100;
    
                double monthlyPayment = 0;
                double numerator = totalLoan * monthlyInterest * pow(1 + monthlyInterest, payments);
                double denominator = pow(1 + monthlyInterest, payments) - 1;
                if (denominator != 0) {
                    monthlyPayment = numerator / denominator;
                }
    
                System.out.printf("Prospect %d: %s wants to borrow %.2f for a period of %d years and pay %.2f€ each month\n", i, name,totalLoan,years,monthlyPayment);
                System.out.println();
                i++;
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public static double pow(double base, int exponent) {
        double result = 1;
        for (int i = 0; i < exponent; i++) {
            result *= base;
        }
        return result;
    }
}
